version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=your-secret-key-should-be-very-long-and-secure-in-production
      - DEV_SECRET_KEY=your-dev-secret-key-for-admin-creation
    depends_on:
      - redis
    networks:
      - logistics-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - logistics-network

volumes:
  redis-data:

networks:
  logistics-network:
    driver: bridge 