# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Test_1user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Configure second-level cache
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          missing_cache_strategy: create
    # Enable batch processing
    jdbc:
      batch_size: 30
      fetch_size: 100
  
  # Redis configuration for local development
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      client-type: lettuce
      connect-timeout: 2000
      repositories:
        enabled: false
  
  cache:
    type: caffeine

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.logistics: TRACE
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n"